name: yes_bank
description: "A new Flutter project."
publish_to: 'none' # Remova esta linha se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  mobx: ^2.0.0
  sqflite: ^2.0.0+3
  flutter_localizations:
    sdk: flutter
  device_preview: ^1.2.0 # Atualizado para a versão 1.2.0 ou superior, compatível com provider 6.x.x

  # Dependência para os ícones Cupertino
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_database:
  firebase_auth: ^5.5.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Certifique-se de que as localizações estão configuradas corretamente
  # Adicione aqui outras configurações de assets ou fontes, se necessário.
