// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45MxnReCWdbwVoAlX9vYpIxl8EAUMyKk',
    appId: '1:852784575462:web:4692489beea97494c91c27',
    messagingSenderId: '852784575462',
    projectId: 'yes-bank-flutter-app',
    authDomain: 'yes-bank-flutter-app.firebaseapp.com',
    storageBucket: 'yes-bank-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGbLVWK5ZR73yRQslS3q-ui-UgjA1J3I',
    appId: '1:852784575462:android:1ca2f4e3478af927c91c27',
    messagingSenderId: '852784575462',
    projectId: 'yes-bank-flutter-app',
    storageBucket: 'yes-bank-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYbRaQAZqKafS0NWwdSNPUg17sZmm8nI',
    appId: '1:852784575462:ios:606809b640a6bf7ac91c27',
    messagingSenderId: '852784575462',
    projectId: 'yes-bank-flutter-app',
    storageBucket: 'yes-bank-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.yesBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBYbRaQAZqKafS0NWwdSNPUg17sZmm8nI',
    appId: '1:852784575462:ios:606809b640a6bf7ac91c27',
    messagingSenderId: '852784575462',
    projectId: 'yes-bank-flutter-app',
    storageBucket: 'yes-bank-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.yesBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45MxnReCWdbwVoAlX9vYpIxl8EAUMyKk',
    appId: '1:852784575462:web:52b76c12657eee96c91c27',
    messagingSenderId: '852784575462',
    projectId: 'yes-bank-flutter-app',
    authDomain: 'yes-bank-flutter-app.firebaseapp.com',
    storageBucket: 'yes-bank-flutter-app.firebasestorage.app',
  );
}
